<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <_RoboticoRepositoryHubPath>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)..\..\..\robotico-repository-csharp\src\Robotico.Repository\Robotico.Repository.csproj'))</_RoboticoRepositoryHubPath>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace>Robotico.Repository.Mishima</RootNamespace>
    <AssemblyName>Robotico.Repository.Mishima</AssemblyName>
    <PackageProjectUrl>https://github.com/robotico-dev/robotico-repository-mishimadocs-csharp</PackageProjectUrl>
    <RepositoryUrl>https://github.com/robotico-dev/robotico-repository-mishimadocs-csharp</RepositoryUrl>
    <RepositoryBranch>main</RepositoryBranch>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" Visible="false" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="All" />
    <PackageReference Include="Robotico.Domain" />
    <PackageReference Include="Robotico.Result" />
  </ItemGroup>
  <ItemGroup Condition="Exists('$(_RoboticoRepositoryHubPath)')">
    <ProjectReference Include="$(_RoboticoRepositoryHubPath)" />
  </ItemGroup>
  <ItemGroup Condition="!Exists('$(_RoboticoRepositoryHubPath)')">
    <PackageReference Include="Robotico.Repository" />
  </ItemGroup>
  <ItemGroup Condition="Exists('$(MishimaDocsProjectPath)')">
    <ProjectReference Include="$(MishimaDocsProjectPath)" />
  </ItemGroup>
  <ItemGroup Condition="!Exists('$(MishimaDocsProjectPath)')">
    <PackageReference Include="MishimaDocs" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Robotico.Repository.Mishima.Tests" />
  </ItemGroup>
</Project>
